version: '3'

services:
    app:
        build: .
        networks:
            - app
        environment:
            DATABASE_URL: mysql://root:root@database:3306/go_http
        depends_on:
            database:
                condition: service_healthy
        ports:
            - '3333:3333'

    database:
        image: mariadb:lts
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: distro_deploy
        volumes:
            - go_http_database:/var/lib/mysql
        healthcheck:
            test:
                [
                    'CMD',
                    '/usr/local/bin/healthcheck.sh',
                    '--su-mysql',
                    '--connect',
                    '--innodb_initialized',
                ]
        networks:
            - app

volumes:
    go_http_database:

networks:
    app:
